name: CD - Continuous Delivery
on:
  push:
    tags:
      - 'v*'

jobs:
  generate-executables:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: "checkout"
      uses: actions/checkout@v3

    - name: "setup node"
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: "extract version from tag"
      id: extract-version
      uses: mad9000/actions-find-and-replace-string@5
      with:
        source: ${{ github.ref_name }}
        find: 'v'
        replace: ''

    - name: "build project"
      run: |
        npm ci && npm run build

    - name: "create version file"
      run: |
        cd dist \
        && touch .version \
        && echo current=${{ github.ref_name }} > .version

    - name: "create binary executables"
      run: npm run release

    - name: "create tar files"
      run: |
        cd artifacts \
        && mv dlq-utils-macos dlq-utils \
        && tar -czf dlq-utils-${{ steps.extract-version.outputs.value }}-darwin-amd64.tar.gz dlq-utils \
        && mv dlq-utils-linux dlq-utils \
        && tar -czf dlq-utils-${{ steps.extract-version.outputs.value }}-linux-amd64.tar.gz dlq-utils \
        && rm dlq-utils

    - name: "upload release assets"
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "artifacts/*"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref_name }}

  deploy-homebrew:
    runs-on: ubuntu-latest
    needs: generate-executables
    steps:
    - name: "release to homebrew"
      uses: Justintime50/homebrew-releaser@v1
      with:
        formula_folder: Formula
        homebrew_owner: leoaugustov
        commit_owner: leoaugustov
        commit_email: vieira.augustoleonardo@gmail.com
        version: ${{ github.ref_name }}
        target_darwin_amd64: true
        target_linux_amd64: true
        homebrew_tap: homebrew-dlq-utils
        install: 'bin.install "dlq-utils"'
        github_token: ${{ secrets.HOMEBREW_TAP_GITHUB_PAT }}
        debug: true
